version: "3.8"

services:
  postgres:
    build: ./postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres_network

  ruby_user_management:
    build: ./ruby_user_management
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/ft_transcendence_db
      SECRET_KEY: ${SECRET_KEY}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      API_CLIENT: ${API_CLIENT42}
      API_SECRET: ${API_SECRET42}
      REDIR_URL: ${REDIR_URL42}
    depends_on:
      - postgres
    volumes:
      - ./ruby_user_management:/app
    networks:
      - nginx_network
      - postgres_network
      - smtp_network

  ruby_ssr:
    build: ./ruby_ssr
    environment:
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - ruby_user_management
    volumes:
      - ./ruby_ssr:/app
    networks:
      - nginx_network

  ruby_pong:
    build: ./ruby_pong
    environment:
      SECRET_KEY: ${SECRET_KEY}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      - postgres
    volumes:
      - ./ruby_pong:/app
    networks:
      - nginx_network

  ruby_friend:
    build: ./ruby_friend
    environment:
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - postgres
    volumes:
      - ./ruby_friend:/app
    networks:
      - nginx_network

  ruby_rgpd:
    build: ./ruby_rgpd
    environment:
      SECRET_KEY: ${SECRET_KEY}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      - postgres
    volumes:
      - ./ruby_rgpd:/app
    ports:
      - "4570:4570"

  ruby_pong_api:
    build: ./ruby_pong_api
    environment:
      SECRET_KEY: ${SECRET_KEY}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      - postgres
    volumes:
      - ./ruby_pong_api:/app
    ports:
      - "4571:4571"
    networks:
      - nginx_network
      - postgres_network

  nginx:
    build: ./nginx
    depends_on:
      - ruby_user_management
      - ruby_ssr
      - ruby_pong
      - ruby_rgpd
      - ruby_pong_api
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nginx_network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    networks:
      - postgres_network

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - "9081:80"
      - "9025:25"
    networks:
      - smtp_network

  mongodb:
    build: ./mongodb
    container_name: mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    networks:
      - mongo_network
    volumes:
      - mongodb_data:/data/db

  image_ruby:
    build: ./image_ruby
    volumes:
      - ./image_ruby:/app
    ports:
      - "4572:4572"
    networks:
      - mongo_network
      - nginx_network

volumes:
  postgres-data:
  mongodb_data:

networks:
  postgres_network:
    driver: bridge
  nginx_network:
    driver: bridge
  smtp_network:
    driver: bridge
  mongo_network:
    driver: bridge
